---
- name: Host Rules Perf
  hosts: all
  sources:
    - name: range
      range:
        limit: 5
  rules:
    - name:
      condition: i == 1
      action:
        assert_fact:
          fact:
            j: 1
    - name:
      condition: i == 2
      action:
        run_playbook:
          name: hello_playbook1.yml
    - name:
      condition: i == 3
      action:
        retract_fact:
          fact:
            j: 3
    - name:
      condition: i == 4
      action:
        post_event:
          fact:
            j: 4
    - name:
      condition: +j
      action:
        none:
